-- Kategoriler (Flutter NewsCategory listesi ile bire bir uyumlu)
INSERT OR REPLACE INTO categories (id, name, icon, color, sort_order) VALUES
  ('gundem',    'Gündem',    'newspaper_outlined',     '#D32F2F',  1),
  ('spor',      'Spor',      'sports_soccer_outlined', '#2E7D32',  2),
  ('ekonomi',   'Ekonomi',   'trending_up_outlined',   '#1565C0',  3),
  ('teknoloji', 'Teknoloji', 'memory_outlined',        '#6A1B9A',  4),
  ('dunya',     'Dünya',     'travel_explore_outlined','#00838F',  5),
  ('kultur',    'Kültür',    'theater_comedy_outlined','#AD1457',  6),
  ('saglik',    'Sağlık',    'favorite_outline',       '#EF6C00',  7),
  ('bilim',     'Bilim',     'science_outlined',       '#283593',  8),
  ('egitim',    'Eğitim',    'school_outlined',        '#558B2F',  9),
  ('yasam',     'Yaşam',     'local_cafe_outlined',    '#8D6E63', 10),
  ('sanat',     'Sanat',     'palette_outlined',       '#512DA8', 11),
  ('seyahat',   'Seyahat',   'flight_takeoff_outlined','#00695C', 12);

INSERT OR IGNORE INTO authors (name, bio) VALUES
  ('Ayşe Yıldız',     'Ekonomi muhabiri'),
  ('Mehmet Kaya',     'Spor editörü'),
  ('Eren Demir',      'Teknoloji yazarı'),
  ('Dr. Selin Aydın', 'Bilim editörü'),
  ('Burak Şahin',     'Şehir muhabiri'),
  ('Cem Aksoy',       'Dış politika muhabiri'),
  ('Defne Aslan',     'Seyahat ve yaşam'),
  ('Dr. Hakan Öz',    'Sağlık editörü'),
  ('Zeynep Korkmaz',  'Eğitim muhabiri'),
  ('Lale Ergin',      'Kültür ve sanat editörü');

-- Örnek makaleler (Flutter mock_news_data ile aynı id'ler)
INSERT OR REPLACE INTO articles
  (id, title, summary, content, category_id, image_url, author_id, published_at, read_minutes, is_featured)
VALUES
  ('a1',
   'Merkez Bankası faiz kararını açıkladı, piyasalar tepki verdi',
   'Para Politikası Kurulu, beklentilerin aksine politika faizini sabit tuttu; borsada hareketlilik gözlendi.',
   'Para Politikası Kurulu, beklentilerin aksine politika faizini sabit tuttu. Borsada gün içi hareketlilik dikkat çekti...',
   'ekonomi',
   'https://picsum.photos/seed/finance1/1200/800',
   (SELECT id FROM authors WHERE name='Ayşe Yıldız'),
   datetime('now', '-12 minutes'),
   4, 1),
  ('a2',
   'Süper Lig''de derbi heyecanı: Galibiyet son dakikada geldi',
   'Nefes kesen mücadele, uzatma dakikalarındaki golle sonuçlandı.',
   'Nefes kesen derbi mücadelesi uzatma dakikalarındaki golle sonuçlandı. Taraftarlar maç sonunda sokakları doldurdu...',
   'spor',
   'https://picsum.photos/seed/soccer1/1200/800',
   (SELECT id FROM authors WHERE name='Mehmet Kaya'),
   datetime('now', '-1 hours'),
   3, 1),
  ('a3',
   'Yapay zekâ destekli yeni nesil işlemci tanıtıldı',
   'Çip üreticisi, mobil cihazlarda yapay zekâ performansını ikiye katlayan modeli duyurdu.',
   'Çip üreticisi, mobil cihazlarda yapay zekâ performansını ikiye katlayan yeni nesil işlemcisini tanıttı...',
   'teknoloji',
   'https://picsum.photos/seed/chip1/1200/800',
   (SELECT id FROM authors WHERE name='Eren Demir'),
   datetime('now', '-2 hours'),
   5, 1),
  ('a4',
   'Mars''tan dönen örneklerde organik bileşikler tespit edildi',
   'Bilim insanları, Kızıl Gezegen''den getirilen örneklerde yaşamın temel taşı sayılan moleküllere ulaştı.',
   'Bilim insanları, Mars''tan getirilen örneklerde organik bileşikler tespit etti. Bulgular önemli bir adım sayılıyor...',
   'bilim',
   'https://picsum.photos/seed/mars1/1200/800',
   (SELECT id FROM authors WHERE name='Dr. Selin Aydın'),
   datetime('now', '-3 hours'),
   6, 1),
  ('a5',
   'İstanbul''da yeni metro hattı hizmete açılıyor',
   'Şehrin doğu-batı aksını birbirine bağlayacak yeni hat günlük 800 bin yolcuya hizmet vermeyi hedefliyor.',
   'İstanbul''un yeni metro hattı bugün hizmete açıldı. Hat, doğu-batı aksında ulaşımı önemli ölçüde rahatlatacak...',
   'gundem',
   'https://picsum.photos/seed/metro1/1200/800',
   (SELECT id FROM authors WHERE name='Burak Şahin'),
   datetime('now', '-5 hours'),
   4, 1),
  ('a6',
   'Avrupa Birliği yeni dijital pazar düzenlemesini kabul etti',
   'AB, dijital pazar üzerindeki yeni regülasyonu onayladı; büyük platformlar için kurallar değişiyor.',
   'AB, dijital pazar düzenlemesini kabul etti. Yeni kurallar büyük teknoloji şirketlerini etkileyecek...',
   'dunya',
   'https://picsum.photos/seed/eu1/1200/800',
   (SELECT id FROM authors WHERE name='Cem Aksoy'),
   datetime('now', '-6 hours'),
   5, 0),
  ('a7',
   'Yaz tatili rotaları: Bu yıl ön plana çıkan 5 sakin koy',
   'Kalabalıktan uzak, doğayla iç içe tatil arayanlar için seçtiğimiz 5 sakin koy.',
   'Bu yıl yaz tatilinde kalabalıktan kaçmak isteyenler için sakin koylardan derlediklerimiz...',
   'seyahat',
   'https://picsum.photos/seed/beach1/1200/800',
   (SELECT id FROM authors WHERE name='Defne Aslan'),
   datetime('now', '-7 hours'),
   4, 0),
  ('a8',
   'Kalp sağlığı için günde 30 dakika yürüyüşün etkisi',
   'Düzenli yürüyüşün kalp damar sağlığı üzerindeki etkileri yeni bir araştırmayla ortaya koyuldu.',
   'Yapılan yeni araştırma, günde 30 dakika yürüyüşün kalp sağlığına etkilerini ortaya koydu...',
   'saglik',
   'https://picsum.photos/seed/walk1/1200/800',
   (SELECT id FROM authors WHERE name='Dr. Hakan Öz'),
   datetime('now', '-8 hours'),
   3, 0),
  ('a9',
   'Üniversite tercih süreci başladı: Adaylar için kritik 7 ipucu',
   'Tercih döneminde adayların dikkat etmesi gereken 7 önemli noktayı uzmanlar değerlendirdi.',
   'Üniversite tercih sürecinde adayların dikkat etmesi gereken kritik noktalar...',
   'egitim',
   'https://picsum.photos/seed/uni1/1200/800',
   (SELECT id FROM authors WHERE name='Zeynep Korkmaz'),
   datetime('now', '-10 hours'),
   6, 0),
  ('a10',
   'Yerli oyun stüdyosu Steam''de zirveye yerleşti',
   'Türk oyun stüdyosunun yeni oyunu çıkışıyla satış listelerinde zirveye oturdu.',
   'Yerli yapım oyun, çıkış gününde Steam''de en çok oynanan oyunlar listesinin zirvesine yerleşti...',
   'teknoloji',
   'https://picsum.photos/seed/game1/1200/800',
   (SELECT id FROM authors WHERE name='Eren Demir'),
   datetime('now', '-12 hours'),
   4, 0),
  ('a11',
   'Şampiyonlar Ligi: Türk takımı çeyrek final hesabı yapıyor',
   'Türk temsilcisi tur eşiğinde önemli bir maça çıkıyor.',
   'Türk takımı, Şampiyonlar Ligi çeyrek final yolunda kritik maça çıkıyor...',
   'spor',
   'https://picsum.photos/seed/soccer2/1200/800',
   (SELECT id FROM authors WHERE name='Mehmet Kaya'),
   datetime('now', '-14 hours'),
   3, 0),
  ('a12',
   'Dolar/TL kuru ve altın fiyatları: Günün son rakamları',
   'Piyasalar günü hareketli kapattı; döviz ve altında son durum.',
   'Piyasalarda günün son rakamları açıklandı. Dolar/TL ve altın fiyatları günü hareketli kapattı...',
   'ekonomi',
   'https://picsum.photos/seed/finance2/1200/800',
   (SELECT id FROM authors WHERE name='Ayşe Yıldız'),
   datetime('now', '-16 hours'),
   2, 0),
  ('a13',
   'Modern sanat sergisi İstanbul Modern''de kapılarını açtı',
   'Yıl sonuna kadar sürecek sergi, yerli ve yabancı sanatçıların eserlerini buluşturuyor.',
   'İstanbul Modern''in yeni sergisi modern sanatın farklı disiplinlerinden eserleri buluşturuyor...',
   'sanat',
   'https://picsum.photos/seed/art1/1200/800',
   (SELECT id FROM authors WHERE name='Lale Ergin'),
   datetime('now', '-18 hours'),
   5, 0),
  ('a14',
   'Yeni nesil elektrikli otomobiller menzil rekoru kırıyor',
   'Pil teknolojisindeki gelişmeler menzili önemli ölçüde artırıyor.',
   'Yeni nesil elektrikli otomobiller pil teknolojisindeki ilerlemelerle menzil rekorlarını yeniliyor...',
   'teknoloji',
   'https://picsum.photos/seed/ev1/1200/800',
   (SELECT id FROM authors WHERE name='Eren Demir'),
   datetime('now', '-20 hours'),
   4, 0),
  ('a15',
   'Kahve kültürü: Üçüncü dalga kafelerin yükselişi',
   'Şehirlerdeki kahve kültürü değişiyor; üçüncü dalga kafeler genç tüketiciyi hedefliyor.',
   'Şehirde kahve kültürü değişiyor. Üçüncü dalga kafeler her geçen gün artıyor...',
   'yasam',
   'https://picsum.photos/seed/coffee1/1200/800',
   (SELECT id FROM authors WHERE name='Defne Aslan'),
   datetime('now', '-22 hours'),
   4, 0),
  ('a16',
   'Kuantum bilgisayarda yeni rekor: 1000 kübitlik sistem',
   'Araştırmacılar, 1000 kübitlik kuantum sistemiyle yeni bir kilometre taşı oluşturdu.',
   'Kuantum bilgisayar alanında 1000 kübitlik sistem tanıtıldı. Bu önemli bir kilometre taşı...',
   'bilim',
   'https://picsum.photos/seed/quantum1/1200/800',
   (SELECT id FROM authors WHERE name='Dr. Selin Aydın'),
   datetime('now', '-1 days'),
   7, 0),
  ('a17',
   'Edebiyat ödülü bu yıl genç bir kadın yazara gitti',
   'Bu yılın edebiyat ödülü ilk romanıyla genç bir kadın yazara verildi.',
   'Edebiyat ödülü bu yıl genç bir yazara gitti. Yazarın ilk romanı kısa sürede çok satanlara girmişti...',
   'kultur',
   'https://picsum.photos/seed/books1/1200/800',
   (SELECT id FROM authors WHERE name='Lale Ergin'),
   datetime('now', '-1 days', '-2 hours'),
   5, 0),
  ('a18',
   'Asya pazarlarında karışık seyir: Yatırımcı temkinli',
   'Asya borsaları gün boyu dalgalı bir seyir izledi; yatırımcı verileri bekliyor.',
   'Asya pazarları gün boyu karışık seyir izledi. Yatırımcılar makro verileri bekliyor...',
   'ekonomi',
   'https://picsum.photos/seed/market1/1200/800',
   (SELECT id FROM authors WHERE name='Ayşe Yıldız'),
   datetime('now', '-1 days', '-4 hours'),
   3, 0),
  ('a19',
   'Japonya''da ileri teknoloji robotlar yaşlı bakımına giriyor',
   'Yaşlı nüfusu yüksek ülke, teknoloji destekli bakım modellerini hayata geçiriyor.',
   'Japonya''da yaşlı nüfusa hizmet için tasarlanan ileri teknoloji robotlar yaygınlaşıyor...',
   'dunya',
   'https://picsum.photos/seed/robot1/1200/800',
   (SELECT id FROM authors WHERE name='Cem Aksoy'),
   datetime('now', '-1 days', '-6 hours'),
   6, 0),
  ('a20',
   'Gece koşusu trendi: Şehirlerde yeni bir spor kültürü',
   'Şehirlerde gece koşusu kulüpleri hızla çoğalıyor.',
   'Şehirlerde gece koşusu kulüpleri hızla yaygınlaşıyor. Sosyalleşme ile sporu birleştiren yeni bir kültür...',
   'spor',
   'https://picsum.photos/seed/run1/1200/800',
   (SELECT id FROM authors WHERE name='Mehmet Kaya'),
   datetime('now', '-1 days', '-8 hours'),
   4, 0),
  ('a21',
   'Sağlıklı uyku için akşam rutini: 6 küçük değişiklik',
   'Daha iyi uyku için akşam rutininizde uygulayabileceğiniz öneriler.',
   'Sağlıklı uyku için akşam rutininizde küçük değişiklikler büyük fark yaratabilir...',
   'saglik',
   'https://picsum.photos/seed/sleep1/1200/800',
   (SELECT id FROM authors WHERE name='Dr. Hakan Öz'),
   datetime('now', '-1 days', '-12 hours'),
   5, 0),
  ('a22',
   'Kapadokya''da balon sezonu rekor sayıyla başladı',
   'Sezon ilk haftasında rekor sayıda turist Kapadokya''yı ziyaret etti.',
   'Kapadokya''da balon sezonu rekor sayıda turistle açıldı. Bölgeye olan ilgi her geçen yıl artıyor...',
   'seyahat',
   'https://picsum.photos/seed/balloon1/1200/800',
   (SELECT id FROM authors WHERE name='Defne Aslan'),
   datetime('now', '-1 days', '-18 hours'),
   3, 0),
  ('a23',
   'STEM eğitimi: Ortaokulda kodlama dersleri yaygınlaşıyor',
   'Müfredata eklenen kodlama dersleri için pilot uygulamalar hız kazanıyor.',
   'Ortaokul müfredatına kodlama dersleri ekleniyor. Pilot okullardaki uygulamalar başladı...',
   'egitim',
   'https://picsum.photos/seed/code1/1200/800',
   (SELECT id FROM authors WHERE name='Zeynep Korkmaz'),
   datetime('now', '-2 days'),
   5, 0),
  ('a24',
   'Tiyatro festivali bu yıl 28 ülkeden topluluğu ağırlıyor',
   'Festival programı bu yıl rekor sayıda yabancı topluluğu sahneye çıkarıyor.',
   'Uluslararası tiyatro festivali bu yıl 28 farklı ülkeden topluluğu sahneye çıkarıyor...',
   'kultur',
   'https://picsum.photos/seed/theatre1/1200/800',
   (SELECT id FROM authors WHERE name='Lale Ergin'),
   datetime('now', '-2 days', '-4 hours'),
   4, 0),
  ('a25',
   'Genç ressamların ortak sergisi: 12 farklı bakış',
   'Genç ressamların ortak sergisi farklı disiplinleri buluşturuyor.',
   'Genç ressamların ortak sergisinde 12 farklı sanatçının eserleri yer alıyor...',
   'sanat',
   'https://picsum.photos/seed/paint1/1200/800',
   (SELECT id FROM authors WHERE name='Lale Ergin'),
   datetime('now', '-2 days', '-8 hours'),
   4, 0),
  ('a26',
   'Uzaktan çalışma kalıcı: Şirketlerin yeni iş modelleri',
   'Şirketler uzaktan ve hibrit çalışma modellerini kalıcı kıldıklarını duyuruyor.',
   'Pandemi sonrası uzaktan çalışma birçok şirkette kalıcı bir uygulama haline geldi...',
   'yasam',
   'https://picsum.photos/seed/remote1/1200/800',
   (SELECT id FROM authors WHERE name='Burak Şahin'),
   datetime('now', '-2 days', '-12 hours'),
   5, 0),
  ('a27',
   'Bulut bilişim pazarında yerli oyuncuların payı artıyor',
   'Yerli bulut sağlayıcıların pazar payı her geçen yıl yükseliyor.',
   'Bulut bilişim pazarında yerli oyuncuların payı her geçen yıl artıyor...',
   'teknoloji',
   'https://picsum.photos/seed/cloud1/1200/800',
   (SELECT id FROM authors WHERE name='Eren Demir'),
   datetime('now', '-3 days'),
   4, 0),
  ('a28',
   'Akdeniz''de yeni arkeolojik buluntular gün yüzüne çıktı',
   'Akdeniz kıyısındaki kazı çalışmalarında önemli bulgulara ulaşıldı.',
   'Akdeniz kıyısındaki kazılarda yeni arkeolojik bulgular gün yüzüne çıkarıldı...',
   'kultur',
   'https://picsum.photos/seed/arch1/1200/800',
   (SELECT id FROM authors WHERE name='Lale Ergin'),
   datetime('now', '-3 days', '-6 hours'),
   6, 0),
  ('a29',
   'Türkiye''nin uydu programı: Yeni nesil görüntüleme uydusu yolda',
   'Yeni nesil görüntüleme uydusunun fırlatma takvimi açıklandı.',
   'Türkiye''nin yeni nesil görüntüleme uydusu için fırlatma tarihi belirlendi...',
   'bilim',
   'https://picsum.photos/seed/satellite1/1200/800',
   (SELECT id FROM authors WHERE name='Dr. Selin Aydın'),
   datetime('now', '-3 days', '-12 hours'),
   5, 0),
  ('a30',
   'Şehir bisikleti ağı genişliyor: Yeni 200 istasyon',
   'Şehir bisikleti ağına 200 yeni istasyon ekleniyor.',
   'Şehir bisikleti ağına yeni 200 istasyon eklenmesiyle ağ önemli ölçüde genişleyecek...',
   'gundem',
   'https://picsum.photos/seed/bike1/1200/800',
   (SELECT id FROM authors WHERE name='Burak Şahin'),
   datetime('now', '-4 days'),
   3, 0);
