import java.io.File

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
    // Firebase google-services.json'ı build'a inject eder.
    // flutterfire configure çalıştırıldıktan sonra google-services.json
    // bu klasöre düşer ve plugin onu kullanır.
    id("com.google.gms.google-services")
}

// ─── .env.json → lib/core/generated/secrets.g.dart ─────────────────────────
// Her Gradle build'inde (flutter build apk dahil) çalışır.
// .env.json gitignored → key asla Git'e girmez.
// Üretilen secrets.g.dart da gitignored → kod temiz kalır.
val generateSecrets by tasks.registering {
    val envFile = File(rootProject.projectDir, "../.env.json")
    val outputFile = File(rootProject.projectDir, "../lib/core/generated/secrets.g.dart")
    doLast {
        outputFile.parentFile.mkdirs()
        val key = if (envFile.exists()) {
            Regex(""""OPENROUTER_API_KEY"\s*:\s*"([^"]+)"""")
                .find(envFile.readText())?.groupValues?.getOrNull(1) ?: ""
        } else ""
        outputFile.writeText(
            "// AUTO-GENERATED by Gradle — .env.json kaynaklı. Commit etme.\n" +
            "// ignore_for_file: prefer_const_declarations\n" +
            "const String kBuiltInOpenRouterApiKey = '$key';\n"
        )
    }
}

tasks.named("preBuild") { dependsOn(generateSecrets) }

android {
    namespace = "com.ethemdemirkaya.pusula"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        // flutter_local_notifications Java 8 API'leri (java.time vs)
        // kullandığı için core library desugaring şart. Bu olmadan
        // "Dependency requires core library desugaring" hatası verir.
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        applicationId = "com.ethemdemirkaya.pusula"
        // flutter_local_notifications + firebase_messaging + audio_session
        // Android API 24+ destekliyor. Flutter default minSdk (21) bazı
        // plugin'lerin requirement'larıyla çakışıyor.
        minSdk = 24
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

dependencies {
    // Java 8+ API'lerinin (java.time, java.util.stream vb.) eski Android
    // API seviyelerine derlenmesi için. flutter_local_notifications zorunlu.
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
}

flutter {
    source = "../.."
}
